/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Laurence Burton 
 */
public class crypt extends javax.swing.JFrame {

    /**
     * Creates new form crypt
     */
    public crypt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        isbn = new javax.swing.JButton();
        creditCard = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clear.setText("Clear");
        clear.setToolTipText("");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });

        isbn.setText("ISBN ");
        isbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isbnMouseClicked(evt);
            }
        });

        creditCard.setText("Credit Card");
        creditCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditCardMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Output:");

        jLabel3.setText("ISBN:");

        jLabel4.setText("Credit Card:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jTextField2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creditCard)))
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(isbn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(creditCard))
                .addGap(29, 29, 29)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
/*  
    Description:    This function runs when the user clicks 
                    the clear button on the user interface. 
                    It will then clear all the text that the
                    user has inputed. 

    Parameters:     java.awt.event.MouseEvent evt  

    Returns:        void
    Author(s):      Laurence Burton (15003639)  
*/
    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        
        //Clear Fields
        jTextField2.setText("");     
        jTextField1.setText("");
        jTextArea1.setText("");



    }//GEN-LAST:event_clearMouseClicked

    /*  
    Description:    This function runs when the user clicks 
                    the ISBN button on the user interface. 
                    It will then take the number the user inputted 
                    and check if it's a valid credit card number

    Parameters:     java.awt.event.MouseEvent evt  

    Returns:        void
    Author(s):      Laurence Burton (15003639)  
*/
    private void isbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isbnMouseClicked
        
        int[] d = new int[10]; 
        int sum = 0;
        String oldString;
	oldString = jTextField1.getText();
        String newString = oldString.replaceAll("-","");

        //Checks the length of the inputted number 
        if(newString.length() == 10){
           jTextArea1.setText("You number is getting processed.");
           //loops through each number. 
            for (int i = 0; i < (d.length);i++){
                d[i] = Integer.parseInt(String.valueOf(newString.charAt(i)));
                //Ever number is multiplied by it's possiton except for the final digit. 
                if(i != 9){              
                    sum = sum +(d[i]*(i+1));
                }
            }
            //The sum is divided by 11 and checked if the remainder equals the final digit. 
            if((sum % 11) == d[9]){
                jTextArea1.setText("Your ISBN number is valid");
            }else{
                jTextArea1.setText("Sorry that number is not valid");
            }
        }else{
                jTextArea1.setText("Sorry that number is not valid");

        }
    }//GEN-LAST:event_isbnMouseClicked
/*  
    Description:    This function runs when the user clicks 
                    the credit card button on the user interface. 
                    It will then take the number the user inputted 
                    and check if it's a valid credit card number

    Parameters:     java.awt.event.MouseEvent evt  

    Returns:        void
    Author(s):      Laurence Burton (15003639)  
*/
    private void creditCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditCardMouseClicked

        int[] d = new int[16]; 
        int sum = 0;
        String oldString;
	oldString = jTextField2.getText();
        String newString = oldString.replaceAll("-","");
        
        //Checks if the inputed string is long enough
        if(newString.length() == 16){
           jTextArea1.setText("You number is getting processed.");
            //Loops through each charater of the inputed string and casts it to an array of ints
            for (int i = 0; i < (d.length);i++){
                d[i] = Integer.parseInt(String.valueOf(newString.charAt(i)));     
                //This doubles every second positions. 
                //It then checks if the results is less 
                //then 10. If not it takes away 9. 
                //Then they're all added together. 
                if((i % 2) == 0){ 
                    if((d[i]*2) > 9){
                        sum += (d[i]*2)- 9;
                    }else{
                        sum += d[i]*2;
                    }
                }else{
                    sum += d[i];
                }
            }
            //The total sum is modded by 10;
            sum = (sum % 10);
            //If the results is 0 then it a valid number
            if(sum == 0){
                jTextArea1.setText("Your Credit Card number is valid");
            }else{
                jTextArea1.setText("Sorry that number is not valid");
            }
        }else{
                jTextArea1.setText("Sorry that number is not valid");

        }

    }//GEN-LAST:event_creditCardMouseClicked
/*  
    Description:    This is the main function for task 1.
                    It's used to declare variables for 
                    the user interface. 
    Parameters:     args the command line arguments  

    Returns:        void
    Author(s):      Laurence Burton (15003639)  
*/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crypt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton creditCard;
    private javax.swing.JButton isbn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
