/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author larry
 */
public class prac extends javax.swing.JFrame {

    /**
     * Creates new form prac
     */
    public prac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      int[] d = new int[10];
      int[] s = new int[4];
  
      int temp, zeroes,p,q,r,i,j,b,a;
        temp = zeroes = 0;
        String text = jTextField1.getText().replaceAll("[^\\d.]", "");
        
        if(text.length() == 10){    
            for(int k = 0; k< 10; k++){
                        d[k]=Integer.parseInt(String.valueOf(text.charAt(k)));
                        System.out.println(d[k]);
            }

            s[0] = ((d[0]+d[1]+d[2]+d[3]+d[4]+d[5]+d[6]+d[7]+d[8]+d[9])%11);
            s[1] = (((d[0]*1)+(d[1]*2)+(d[2]*3)+(d[3]*4)+(d[4]*5)+(d[5]*6)+(d[6]*7)+(d[7]*8)+(d[8]*9)+(d[9]*10))%11);
            s[2] = (((d[0]*1)+(d[1]*4)+(d[2]*9)+(d[3]*5)+(d[4]*3)+(d[5]*3)+(d[6]*5)+(d[7]*9)+(d[8]*4)+(d[9]))%11);
            s[3] = (((d[0])+(d[1]*8)+(d[2]*5)+(d[3]*9)+(d[4]*4)+(d[5]*7)+(d[6]*2)+(d[7]*6)+(d[8]*3)+(d[9]*10))%11);

//            System.out.println(s[0]+" "+s[1]+" "+s[2]+" "+s[3]);

            for (int k = 0; k < 4; k++) {
               if(s[k] == 10){
//                  temp = 1;
                  jTextArea1.setText("Sorry but that is a unusable number");
                  return;
               } else if (s[k] == 0) {
                   zeroes++;
                   
               }else{
                   temp = 1;
               }
            }
            if (zeroes == 4) {
                jTextArea1.setText("No Errors.\n Result is: " + d[0]+d[1]+d[2]+d[3]+d[4]+d[5]+d[6]+d[7]+d[8]+d[9]);
                return;
            } else {          
                int temp3 = 0;
                int temp1 = lookup[2][((s[1])%11)];
                int temp2 = (s[0]*s[2])%11;
                System.out.println(temp2);
//                int temp3 = lookup[1][temp2];
//                temp3 = (temp1) + (temp3);
                p = mod11(temp1 - temp2);// %11;
                
                temp1 = (s[0]*s[3])%11;
                temp2 = (s[1]*s[2])%11;
//                temp3 = lookup[1][temp2];
                q = mod11(temp1 - temp2);
                
                temp1 = lookup[2][((s[2])%11)];
                temp2 = (s[1]*s[3])%11;
//                temp3 = lookup[1][temp2];
                r = mod11(temp1 + temp2);
                
                System.out.println("P: " + p + "Q: " + q + "R: " + r);

                if(p == 0 && q == 0 && r == 0){
                    jTextArea1.setText("You have got 1 error");
                    a = s[0];//magnotide
                    temp1 = (s[0]%11);
                    temp2 = lookup[4][temp1];
                    i = (s[1]*temp2)%11;//position
                    d[i-1] = (d[i-1]-(a));
                    jTextArea1.setText("You had one error in possition "+ i + " With an error magnotude of "+ a +".\n Result is: " + d[0]+d[1]+d[2]+d[3]+d[4]+d[5]+d[6]+d[7]+d[8]+d[9]);
                }else{
//                    int negativeQ = (lookup[1][q])%11;//
                    int squaredQ = (lookup[2][q])%11;
                    int negative4  = (lookup[1][3])%11;
                    temp1 = ((squaredQ + negative4) * (p*r));
                    int squareRoot = sqaureRoot((mod11(squaredQ - 4))*(p*r));
//                            ookup[3][temp1%11];
                    temp1 = negative4 + squareRoot;
                    int inverseVar = inverseNumber(p*2);
                    i = ( -q +squareRoot )*inverseVar;//(temp1 * temp2)%11;
                    
                    
//                    negativeQ = lookup[1][q];//
                    squaredQ = lookup[2][q];
                    negative4  = lookup[1][3];
                    temp1 = ((squaredQ + negative4) * (p*r));
                    squareRoot = lookup[3][temp1%11];
//                    temp1 = negative4 + squareRoot;
//                    temp2 = lookup[4][(p*2)%11];
                   
                    temp1 = lookup[1][mod11(squareRoot)];
                    temp2 = mod11(negative4 - temp1);
                    temp3 = lookup[4][(p*2)%11];
                    j = (temp2 * temp3)%11;
                    
                    
                    int temp4 = i + lookup[1][(j%11)];
                    b = (i*s[1]-lookup[1][(s[2]%11)])*(lookup[3][temp4%11]);
                    a = s[0] + lookup[1][(b%11)];
                    
                    d[i-1] = d[i-1]-(a);
                    d[j-1] = d[j-1]-(b);

                    jTextArea1.setText("I: " + i + " a: " + a+ " J: " + j + " b: " + temp1);
                    System.out.println("I: " + i + " a: " + a+ " J: " + j + " b: " + b);

                  

                }
                        
                
            }
        } else {
            jTextArea1.setText("Please enter a 6 digit number");

        }
    }//GEN-LAST:event_jButton1MouseClicked
    
    public int[][] lookup = { 
           {0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, //0: x
           {0,10, 9, 8, 7, 6, 5, 4, 3, 2, 1}, //1: -x
           {0,1, 4, 9, 5, 3, 3, 5, 9, 4, 1},  //2: x^2
           {0,1, -1, 5, 2, 4, -1, -1, -1, 3, -1},  //3: square root of x
           {0,1, 6, 4, 3, 9, 2, 8, 7, 5, 10}  //4:x^-1(inverse)
        }; 
    
    public int subtract(int a, int b){
        return (a + (-b))%12;
    }
    
    public int inverseNumber(int x){
        return lookup[4][x];
    }
    
    public int sqaureRoot(int x){
        
        x = lookup[3][x];
        if (x == -1){
            jTextArea1.setText("Unusable number");  
            System.exit(0);
        }
        return x;
    }
    
    
    public int mod11(int x){
        x = x%11;
        System.out.print(" " + x);
        if (x < 0){
            x = Math.abs(x);
            x = lookup[1][x];
        }
        return x;
    }
    
    public int inverse(int a, int n) { 
	int t = 0; int newt = 1; 
	int r = n; int newr = a;    int q, temp;  
	while(newr != 0) { 
		q = r / newr;  /* integer division */        
		temp = newt;   /* remember newt    */
		newt = t - q*newt;
		t = temp;
		temp = newr;   /* remember newr    */
		newr = r - q*newr;
		r = temp;
	} 
 	if(r > 1) return -1; /* not invertible */
	if(t < 0) t = t + n; /* change to positive */
	return t;
}
    
    
    public int divide(int a, int b){
        return a *(-b);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
