/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author larry
 */
public class prac extends javax.swing.JFrame {

    /**
     * Creates new form prac
     */
    public prac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Check");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Comments");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("A:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("B:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("J");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("I:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("0");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Syn:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("0000");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Output:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("0000000000");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("P:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Q:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("R:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("0");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("0");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel17)
                        .addComponent(jLabel15)
                        .addComponent(jLabel18)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int[] d = new int[10];
        int[] s = new int[4];
        setup();
        int temp, zeroes,p,q,r,i,j,b,a;
        temp = zeroes = 0;
        String text = jTextField1.getText().replaceAll("[^\\d.]", "");

        if(text.length() == 10){//Check is input is 10 characters    
            for(int k = 0; k< 10; k++){//Loops through input
                        d[k]=Integer.parseInt(String.valueOf(text.charAt(k)));//read numbers into array as ints
            }
            //Generate syndromes
            s[0] = ((d[0]+d[1]+d[2]+d[3]+d[4]+d[5]+d[6]+d[7]+d[8]+d[9])%11);
            s[1] = (((d[0]*1)+(d[1]*2)+(d[2]*3)+(d[3]*4)+(d[4]*5)+(d[5]*6)+(d[6]*7)+(d[7]*8)+(d[8]*9)+(d[9]*10))%11);
            s[2] = (((d[0]*1)+(d[1]*4)+(d[2]*9)+(d[3]*5)+(d[4]*3)+(d[5]*3)+(d[6]*5)+(d[7]*9)+(d[8]*4)+(d[9]))%11);
            s[3] = (((d[0])+(d[1]*8)+(d[2]*5)+(d[3]*9)+(d[4]*4)+(d[5]*7)+(d[6]*2)+(d[7]*6)+(d[8]*3)+(d[9]*10))%11);
            
            jLabel10.setText(s[0]+""+s[1]+""+s[2]+""+s[3]+""); //Output Syndroms to lable

            for (int k = 0; k < 4; k++) {//Loops through syndroms
               if(s[k] == 10){//Checks if any syn is greater then 11
                    jTextArea1.setText("There are more then 2 errors.");                       
                  return;
               } else if (s[k] == 0) {
                   zeroes++;
               }
//               else{
//                   temp = 1;
//               }
            }
            if (zeroes == 4) {
                jTextArea1.setText("You have got no errors.");
                jLabel12.setText(d[0]+""+d[1]+""+d[2]+""+d[3]+""+d[4]+""+d[5]+""+d[6]+""+d[7]+""+d[8]+""+d[9]+""); //Output
            } else {              
                p = generateP(s[0],s[1],s[2]);
                q = generateQ(s[0],s[1],s[2],s[3]);
                r = generateR(s[1],s[2],s[3]);
                
                jLabel16.setText(p + ""); //P        
                jLabel17.setText(q + ""); //Q
                jLabel18.setText(r+ ""); //R

                if(p == 0 && q == 0 && r == 0){
                    jTextArea1.setText("You have got 1 error");
                    a = s[0];//magnotide
                    int temp1 = (s[0]%11);
                    int temp2 = lookup[4][temp1];
                    i = (s[1]*temp2)%11;//position
                    d[i-1] = (d[i-1]-(a));
                    
                    jLabel7.setText(i+""); //I
                    jLabel5.setText(a+"");//A
                    jLabel12.setText(d[0]+""+d[1]+""+d[2]+""+d[3]+""+d[4]+""+d[5]+""+d[6]+""+d[7]+""+d[8]+""+d[9]+""); //Output

                }else{
                    i = generateI(p, q, r);
                    jLabel7.setText(i+""); //I
                    j = generatej(p,q,r);
                    jLabel8.setText(j+""); //J

                    b = generateB(i, s[0],s[1],j);
                    jLabel6.setText(b+""); //B
                    a = generateA(s[0],b);
                    jLabel5.setText(a+"");//A

                    if(i == -1 || j == -1){
                       jTextArea1.setText("There are more then 2 errors and there is no square root.");                       

                    }else{
                        i = i - 1;
                        j = j - 1;

                        if (i == -1){
                            i = 0;
                        }
                        if (j == -1){
                            j = 0;
                        }
                        d[i-1] = mod11(d[i]-a);
                        d[j-1] = mod11(d[j]-b);
                        jTextArea1.setText("You had two errors");

                        jLabel12.setText(d[0]+""+d[1]+""+d[2]+""+d[3]+""+d[4]+""+d[5]+""+d[6]+""+d[7]+""+d[8]+""+d[9]+""); //Output

                    }

                }
                        
                
            }
        } else {
            jTextArea1.setText("Please enter a 6 digit number");

        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void setup(){
        jLabel5.setText("0"); //A       
        jLabel6.setText("0"); //B
        jLabel7.setText("0"); //I
        jLabel8.setText("0"); //J
        jLabel10.setText("0"); //Syn
        jLabel12.setText("0"); //Output       
        jLabel16.setText("0"); //Output        
        jLabel17.setText("0"); //Output
        jLabel18.setText("0"); //Output



    }
    public int generateP(int s1, int s2, int s3){
        int temp1 = lookup[2][((s2)%11)];
        int temp2 = mod11(s1*s3);
        int p = mod11(temp1 - temp2);// %11;
        return p;
    }
    
    
    public int generateQ(int s1, int s2, int s3, int s4){
        int temp1 = (s1*s4)%11;
        int temp2 = (s2*s3)%11;
        int q = mod11(temp1 - temp2);
        return q;
    }

    public int generateR(int s2, int s3, int s4){
        int s3Squared = lookup[2][((s3)%11)];
        int s2AndS4 = mod11(s2*s4);
        int r = mod11(s3Squared - s2AndS4);

        return r;
    }

    public int generateI(int p, int q, int r){
            int squaredQ = sqaureNumber(q);//sqauring Q
            int sum = (squaredQ-(4*(p*r))); //subtract 4 from q^2 and time it by p*r
            int squareRoot = sqaureRoot(sum);
            if(squareRoot == -1){
               jTextArea1.setText("There are more then 2 error");
               return squareRoot;
            }
            System.out.print("Sum:" + squareRoot + " -q: " + -q);
            sum = (-q) + squareRoot;
            int inverseVar = inverseNumber(p*2);
            int i = ( sum )*inverseVar;//(temp1 * temp2)%11;
            return mod11(i);
    }
    
       public int generatej(int p, int q, int r){
            int squaredQ = sqaureNumber(q);//sqauring Q
            int sum = (squaredQ-(4*(p*r))); //subtract 4 from q^2 and time it by p*r
            int squareRoot = sqaureRoot(sum);
            if(squareRoot == -1){
               jTextArea1.setText("There are more then 2 error");
               return squareRoot;
            }
            sum = (-q) - squareRoot;
            int inverseVar = inverseNumber(p*2);
            int i = ( sum )*inverseVar;//(temp1 * temp2)%11;
            return mod11(i);
    }
    
    public int generateB(int i, int s1, int s2 ,int j){
        
        int tempA = (i*s1);
        int tempB = tempA - s2;
        int tempC = mod11(i - j);
        int b = tempB * inverseNumber(tempC);
        return mod11(b);
    }
    public int generateA(int s1,int b){
        int a = s1 - b;
        return mod11(a);
    }
    public int[][] lookup = { 
           {0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, //0: x
           {0,10, 9, 8, 7, 6, 5, 4, 3, 2, 1}, //1: -x
           {0,1, 4, 9, 5, 3, 3, 5, 9, 4, 1},  //2: x^2
           {0,1, -1, 5, 2, 4, -1, -1, -1, 3, -1},  //3: square root of x
           {0,1, 6, 4, 3, 9, 2, 8, 7, 5, 10}  //4:x^-1(inverse)
        }; 
    
    public int subtract(int a, int b){
        return (a + (-b))%12;
    }
    
    public int sqaureNumber(int x){
        x = mod11(x);;
        x = lookup[2][x];
        return x;
                
    }
    
    public int inverseNumber(int x){
        return lookup[4][mod11(x)];
    }
    
    public int sqaureRoot(int x){

        x = mod11(x);
        x = lookup[3][x];

        if (x == -1){
            return x;
        }
        return x;
    }
    
    
    public int mod11(int x){
        x = x%11;
        if (x < 0){
            x = Math.abs(x);
            x = lookup[1][x];
        }
              System.out.print(" " + x);

        return x;
    }
    
    public int inverse(int a, int n) { 
	int t = 0; int newt = 1; 
	int r = n; int newr = a;    int q, temp;  
	while(newr != 0) { 
		q = r / newr;  /* integer division */        
		temp = newt;   /* remember newt    */
		newt = t - q*newt;
		t = temp;
		temp = newr;   /* remember newr    */
		newr = r - q*newr;
		r = temp;
	} 
 	if(r > 1) return -1; /* not invertible */
	if(t < 0) t = t + n; /* change to positive */
	return t;
}
    
    
    public int divide(int a, int b){
        return a *(-b);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
